spring:
  config:
    activate:
      on-profile: dev

aws:
  endpoint: '${DYNAMODB_ENDPOINT:http://localhost:4566}'
  accessKeyId: '${AWS_ACCESS_KEY_ID:dummy}'
  secretKey: '${AWS_SECRET_ACCESS_KEY:dummy}'

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true