server:
  port: 8081

spring:
  application:
    name: cep-acl

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

api:
  viacep:
    timeout-seconds: 5

aws:
  region: ${AWS_REGION:sa-east-1}

---
spring:
  profiles:
    active: dev

aws:
  endpoint: http://localhost:4566
  accessKeyId: dummy
  secretKey: dummy
