spring:
  profiles:
    default: prod

  application:
    name: cep-acl

server:
  port: '${SERVER_PORT:8080}'

aws:
  region: ${AWS_DEFAULT_REGION:sa-east-1}

api:
  viacep:
    url: 'https://viacep.com.br/ws'
    timeout-seconds: 5

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
