server:
  port: 8081

spring:
  application:
    name: cep-acl
  devtools.restart.additional-exclude: "software.amazon.awssdk.**"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

api:
  viacep:
    timeout-seconds: 5

aws:
  region: ${AWS_REGION:sa-east-1}

---
spring:
  config:
    activate:
      on-profile: dev

aws:
  endpoint: http://localhost:4566
