# Lint, Build, Test do artefato
name: Build

on:
  push:
    branches:
      - main
      - heroku
      - aws

env:
  ARTIFACT_FILE: deploy.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepara JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Prepara Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint
        run: ./gradlew checkstyleMain checkstyleTest
        continue-on-error: true

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Testes/Cobertura
        run: ./gradlew coverage --no-daemon

      - name: Prepara artefato
        run: >
          rsync -av
          --include='build/'
          --include='Procfile'
          --include='.ebextensions'
          --exclude='*'
          ./ ${{ ARTIFACT_FILE }}/

      - name: Verifica artefato
        run: tree ${{ ARTIFACT_FILE }}/

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: ${{ env.ARTIFACT_FILE }}/