# Deploy to Render
name: Deploy Render

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

env:
  ZIP_FILE: deploy.zip

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: deploy
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verifica artefato baixado
        run: tree ${{ env.ZIP_FILE }}

      - name: Deployment status
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "🚀 Deploy successful!"
          else
            echo "❌ Deploy failed!"
            exit 1
          fi