# Deploy to Heroku
name: Deploy Heroku

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

env:
  ZIP_FILE: deploy.zip

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'heroku' }}

    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: deploy
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Artefato
        run: unzip -l ${{ env.ZIP_FILE }} | grep -E "^.*[[:space:]]+[^/]+/?$"

      - name: Deployment status
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "🚀 Deploy successful!"
          else
            echo "❌ Deploy failed!"
            exit 1
          fi